/**
 * GEMINI ENGINE - SCAFFOLD, NOT YET VERIFIED.
 *
 * generated by scripts/make-engine-scaffold.cjs
 *
 * WHAT IS DONE
 *   - the full engine contract, so the gateway will load, probe and call this
 *   - conversation state handling, including an explicit newChat reset
 *   - failure classification (waf / auth / upstream) so the caller can decide
 *     between waiting and re-authenticating
 *   - empty-response discipline, so the gateway's retry logic can see "no answer yet"
 *
 * WHAT IS NOT DONE
 *   the wire details: gemini's private web API endpoint, request body and
 *   response shape. These cannot be written blind. Observe them in a real browser
 *   session, fill in the three TODO blocks, then set verified: true.
 *
 * Until then this engine REFUSES to issue a request rather than guessing a path. A
 * scaffold that issued requests to an invented endpoint would fail at runtime with a
 * 404 that looks like a provider problem.
 *
 * ---------------------------------------------------------------------------
 * AUTH MODEL
 *   Login is cookie-injection only (EditThisCookie or Cookie-Editor export). Google sets many non-auth cookies, so auth is judged by the presence of a specific session cookie name, never by a count.
 *
 * CONVERSATION STATE
 *   A conversation is addressed by an id returned with each turn.
 * ---------------------------------------------------------------------------
 */
(function () {
    'use strict';

    var GLOBAL = '__proximaGemini';
    var ORIGIN = 'https://gemini.google.com';

    // ---- operator fills these three in after observing the real API ------------

    var ENDPOINTS = {
        // e.g. { send: '/backend-api/conversation', conversations: '/backend-api/conversations' }
        send: null,
        conversations: null,
    };

    /**
     * Flip to true only after ENDPOINTS are filled in and verified against a live
     * session. The guard below makes an unverified engine fail loudly rather than
     * silently issuing a request to a path that does not exist.
     */
    var verified = false;

    // ---- end of operator-filled configuration ----------------------------------

    var state = {
        conversationId: null,
        organizationId: null,
        lastResponse: '',
        typing: false,
        startedAt: null,
    };

    function nowIso() {
        return new Date().toISOString();
    }

    function notVerified(detail) {
        var e = new Error(
            'gemini engine is a scaffold: ' + detail +
            ' Fill in ENDPOINTS in gemini-engine.js after observing the real API, ' +
            ' then set verified = true.'
        );
        e.kind = 'engine-unverified';
        e.retryable = false;
        return e;
    }

    function assertVerified(method) {
        if (!verified || !ENDPOINTS.send) {
            throw notVerified(method + '() has no verified endpoint');
        }
    }

    function isReady() {
        return verified;
    }

    function isLoggedIn() {
        // Cheap local signal only. The authoritative check is the gateway's
        // name-and-domain matched cookie evaluation, not a substring guess.
        return document.cookie.length > 0;
    }

    function newConversation() {
        // Must clear per-engine state. Without this an automated turn can land as the
        // next message in whatever thread the engine last used.
        state.conversationId = null;
        state.organizationId = null;
        state.lastResponse = '';
        state.startedAt = null;
        return { cleared: true };
    }

    function getConversation() {
        return {
            conversationId: state.conversationId,
            organizationId: state.organizationId,
            startedAt: state.startedAt,
        };
    }

    function getResponse() {
        // Returning an empty string here is correct and load-bearing: the gateway
        // treats '' and the 'no response' sentinels as "retry", anything else as final.
        // Fabricating a value here would defeat that and hand the operator a lie.
        return state.lastResponse;
    }

    function getTypingStatus() {
        return { typing: state.typing };
    }

    function classify(status) {
        if (status === 403 || status === 429) return { kind: 'waf', retryable: true };
        if (status === 401) return { kind: 'auth', retryable: false };
        if (status >= 500) return { kind: 'upstream', retryable: true };
        return { kind: 'unknown', retryable: false };
    }

    async function sendMessage(options) {
        options = options || {};
        if (typeof options.message !== 'string' || !options.message.trim()) {
            throw new Error('sendMessage requires a non-empty message');
        }
        assertVerified('sendMessage');

        state.typing = true;
        state.lastResponse = '';
        state.startedAt = state.startedAt || nowIso();

        try {
            // Same-origin, credentials included. The browser attaches the profile's
            // session cookies and origin clearance, which is the entire point.
            //
            // TODO(block 1 of 3): replace this body with the real request. Observe it in
            // a browser devtools network tab while sending a message by hand.
            var res = await fetch(ENDPOINTS.send, {
                method: 'POST',
                credentials: 'include',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    message: options.message,
                    // TODO(block 2 of 3): real field names for this provider.
                }),
            });

            if (!res.ok) {
                var failure = classify(res.status);
                var err = new Error(
                    'gemini send failed: ' + failure.kind + ' (status ' + res.status + ')'
                );
                err.kind = failure.kind;
                err.retryable = failure.retryable;
                err.status = res.status;
                throw err;
            }

            // TODO(block 3 of 3): extract the answer and the conversation id.
            var data = await res.json().catch(function () { return null; });
            state.conversationId = (data && (data.conversationId || data.conversation_id)) || state.conversationId;
            state.organizationId = (data && (data.organizationId || data.organization_id)) || state.organizationId;
            state.lastResponse = extractText(data);

            return {
                conversationId: state.conversationId,
                length: state.lastResponse.length,
            };
        } finally {
            state.typing = false;
        }
    }

    function extractText(data) {
        // Conservative on purpose: when in doubt return ''. An empty string makes the
        // gateway retry; a wrong guess would be returned to the operator as an answer.
        if (!data) return '';
        if (typeof data.text === 'string') return data.text;
        if (typeof data.answer === 'string') return data.answer;
        if (typeof data.content === 'string') return data.content;
        if (Array.isArray(data.content)) {
            return data.content
                .map(function (c) {
                    if (typeof c === 'string') return c;
                    return c && typeof c.text === 'string' ? c.text : '';
                })
                .filter(Boolean)
                .join('\n');
        }
        return '';
    }

    var api = {
        sendMessage: sendMessage,
        newConversation: newConversation,
        getConversation: getConversation,
        getResponse: getResponse,
        getTypingStatus: getTypingStatus,
        isReady: isReady,
        isLoggedIn: isLoggedIn,
        verified: function () { return verified; },
        version: '0.1.0-scaffold',
    };

    // No upload surface: this provider is login + message only.

    // Overwrite on re-eval. The gateway re-injects on every navigation, and a stale
    // engine must never survive into the next document.
    window[GLOBAL] = api;
})();
